spring:
  application:
    name: wanted-pre-onboarding-backend
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Wkdrn123
    url: jdbc:mysql://localhost:3306/wanted
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
